# Generated by Django 5.1.5 on 2025-02-05 10:46

import crypto.utils
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crypto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Crypto Ticker used for querying from CoinMarketCap",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Used as the header when charting", max_length=64
                    ),
                ),
                (
                    "show_overall",
                    models.BooleanField(
                        default=False,
                        help_text="Show overall value instead of current price",
                    ),
                ),
                (
                    "show_chart",
                    models.BooleanField(
                        default=False,
                        help_text="Show 7-day chart with price trend on Dashboard",
                        verbose_name="Chart crypto",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="crypto/default.png",
                        upload_to=crypto.utils.crypto_image_path,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Hides crypto from Dashboard and does not pull further information",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=999)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("added", models.DateTimeField(auto_now_add=True)),
                (
                    "signal",
                    models.CharField(
                        choices=[
                            ("buy", "Buy"),
                            ("sell", "Sell"),
                            ("hold", "On Hold"),
                            ("none", "No Signal"),
                        ],
                        default="none",
                        help_text="Trading signal for this cryptocurrency",
                        max_length=10,
                    ),
                ),
                (
                    "signal_description",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about the trading signal",
                    ),
                ),
            ],
            options={"ordering": ("order", "symbol"),},
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.FloatField(
                        help_text="Price of crypto in target currency to surpass"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "crypto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="crypto.crypto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Alert",
                "verbose_name_plural": "Price Alerts",
            },
        ),
        migrations.CreateModel(
            name="CryptoData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_price", models.FloatField()),
                ("source_currency", models.CharField(max_length=4)),
                ("target_price", models.FloatField()),
                ("target_currency", models.CharField(max_length=4)),
                (
                    "percent_day",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="24h Percentual Change",
                    ),
                ),
                ("rank", models.PositiveIntegerField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "crypto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="crypto.crypto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Data",
                "verbose_name_plural": "Price Data",
                "get_latest_by": "timestamp",
            },
        ),
        migrations.CreateModel(
            name="CryptoPurchases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("buy_price", models.FloatField()),
                ("buy_currency", models.CharField(max_length=4)),
                ("target_price", models.FloatField(blank=True, null=True)),
                ("target_currency", models.CharField(blank=True, max_length=4)),
                (
                    "bought_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "crypto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="crypto.crypto",
                    ),
                ),
            ],
            options={"verbose_name": "Purchase", "verbose_name_plural": "Purchases",},
        ),
    ]
